In [1]:
# import library
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import plotly.express as px 
from datetime import datetime
import os
from sklearn.model_selection import train_test_split
%matplotlib inline

In [2]:
# tabel setting
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
pd.set_option('display.precision', 2)
pd.options.display.float_format = '{:,.2f}'.format

In [3]:
dataset_dir = '../../Dataset/'

# Sensor 1

In [4]:
sensor1_train = pd.read_csv(dataset_dir + 'train1_encoded.csv')

In [5]:
sensor1_train.head()

,Dur,Proto,SrcAddr,Sport,Dir,DstAddr,Dport,State,sTos,dTos,TotPkts,TotBytes,SrcBytes,Label,StartTimeHour,StartTimeMinute,StartTimeSecond,isBotnet,isSpam
0,0.00,4,1,105,3,994426,955188,15,0,0,2,135,75,0,11,44,44,0,0
1,123.08,3,9998,60,0,1913,489667,103,0,0,10,1302,896,0,9,5,32,0,0
2,"3,084.69",4,2,62,3,994426,955188,15,0,0,4,270,150,0,12,38,18,0,0
3,0.07,3,46,98,0,3386,2870,103,0,0,9,651,369,0,13,42,35,0,0
4,577.48,4,1,86,3,994426,955188,15,0,0,8,1062,307,0,9,15,24,0,0

In [6]:
sensor1_train.shape

(3391396, 19)

## isBotnet

In [7]:
sensor1_isbotnet = sensor1_train.copy()
sensor1_isbotnet.head()

,Dur,Proto,SrcAddr,Sport,Dir,DstAddr,Dport,State,sTos,dTos,TotPkts,TotBytes,SrcBytes,Label,StartTimeHour,StartTimeMinute,StartTimeSecond,isBotnet,isSpam
0,0.00,4,1,105,3,994426,955188,15,0,0,2,135,75,0,11,44,44,0,0
1,123.08,3,9998,60,0,1913,489667,103,0,0,10,1302,896,0,9,5,32,0,0
2,"3,084.69",4,2,62,3,994426,955188,15,0,0,4,270,150,0,12,38,18,0,0
3,0.07,3,46,98,0,3386,2870,103,0,0,9,651,369,0,13,42,35,0,0
4,577.48,4,1,86,3,994426,955188,15,0,0,8,1062,307,0,9,15,24,0,0

In [8]:
sensor1_isbotnet = sensor1_isbotnet.drop(columns=['Label', 'isSpam'])

In [9]:
sensor1_isbotnet.head()

,Dur,Proto,SrcAddr,Sport,Dir,DstAddr,Dport,State,sTos,dTos,TotPkts,TotBytes,SrcBytes,StartTimeHour,StartTimeMinute,StartTimeSecond,isBotnet
0,0.00,4,1,105,3,994426,955188,15,0,0,2,135,75,11,44,44,0
1,123.08,3,9998,60,0,1913,489667,103,0,0,10,1302,896,9,5,32,0
2,"3,084.69",4,2,62,3,994426,955188,15,0,0,4,270,150,12,38,18,0
3,0.07,3,46,98,0,3386,2870,103,0,0,9,651,369,13,42,35,0
4,577.48,4,1,86,3,994426,955188,15,0,0,8,1062,307,9,15,24,0

In [10]:
sensor1_isbotnet.to_csv(dataset_dir + 'sensor1_isbotnet.csv', index=False)

## isSpam

In [11]:
sensor1_isspam = sensor1_train.copy()
sensor1_isspam = sensor1_isspam[sensor1_isspam['isBotnet'] == 1]
sensor1_isspam.head()

,Dur,Proto,SrcAddr,Sport,Dir,DstAddr,Dport,State,sTos,dTos,TotPkts,TotBytes,SrcBytes,Label,StartTimeHour,StartTimeMinute,StartTimeSecond,isBotnet,isSpam
95,3.68,3,62058,55,0,2289,2289,103,0,0,14,852,486,1,16,19,40,1,0
117,8.99,3,62058,67,0,110,4326,285,0,0,3,186,186,2,10,13,48,1,1
128,93.64,3,62058,94,0,826,15277,112,0,0,12,2348,2162,1,15,33,32,1,0
176,"3,250.40",3,62058,204,0,216,216,169,0,0,8656,542023,259200,1,16,5,56,1,0
178,60.00,3,62058,3307,0,5246,489667,275,0,0,8,1687,500,1,13,11,57,1,0

In [12]:
sensor1_isspam = sensor1_isspam.drop(columns=['Label', 'isBotnet'])

In [13]:
sensor1_isspam.head()

,Dur,Proto,SrcAddr,Sport,Dir,DstAddr,Dport,State,sTos,dTos,TotPkts,TotBytes,SrcBytes,StartTimeHour,StartTimeMinute,StartTimeSecond,isSpam
95,3.68,3,62058,55,0,2289,2289,103,0,0,14,852,486,16,19,40,0
117,8.99,3,62058,67,0,110,4326,285,0,0,3,186,186,10,13,48,1
128,93.64,3,62058,94,0,826,15277,112,0,0,12,2348,2162,15,33,32,0
176,"3,250.40",3,62058,204,0,216,216,169,0,0,8656,542023,259200,16,5,56,0
178,60.00,3,62058,3307,0,5246,489667,275,0,0,8,1687,500,13,11,57,0

In [14]:
sensor1_isspam.to_csv(dataset_dir + 'sensor1_isspam.csv', index=False)

# Sensor 2

In [15]:
sensor2_train = pd.read_csv(dataset_dir + 'train2_encoded.csv')

In [16]:
sensor2_train.head()

,Dur,Proto,SrcAddr,Sport,Dir,DstAddr,Dport,State,sTos,dTos,TotPkts,TotBytes,SrcBytes,Label,StartTimeHour,StartTimeMinute,StartTimeSecond,isBotnet,isSpam
0,20.00,3,14610,75,0,141,581761,82,0,0,7,424,242,0,11,43,1,0,0
1,0.00,4,462414,109,3,1621520,1645689,16,0,0,2,240,95,0,9,25,52,0,0
2,0.00,4,1,63,3,1212234,1166534,16,0,0,2,131,71,0,10,29,47,0,0
3,0.07,3,462414,83,0,100,581761,104,0,0,10,2401,1000,0,9,28,36,0,0
4,0.00,4,811174,68,3,1621520,1645689,16,0,0,2,214,81,0,9,42,20,0,0

In [18]:
sensor2_train.shape

(4106701, 19)

## isBotnet

In [19]:
sensor2_isbotnet = sensor2_train.copy()
sensor2_isbotnet.head()

,Dur,Proto,SrcAddr,Sport,Dir,DstAddr,Dport,State,sTos,dTos,TotPkts,TotBytes,SrcBytes,Label,StartTimeHour,StartTimeMinute,StartTimeSecond,isBotnet,isSpam
0,20.00,3,14610,75,0,141,581761,82,0,0,7,424,242,0,11,43,1,0,0
1,0.00,4,462414,109,3,1621520,1645689,16,0,0,2,240,95,0,9,25,52,0,0
2,0.00,4,1,63,3,1212234,1166534,16,0,0,2,131,71,0,10,29,47,0,0
3,0.07,3,462414,83,0,100,581761,104,0,0,10,2401,1000,0,9,28,36,0,0
4,0.00,4,811174,68,3,1621520,1645689,16,0,0,2,214,81,0,9,42,20,0,0

In [20]:
sensor2_isbotnet = sensor2_isbotnet.drop(columns=['Label', 'isSpam'])

In [21]:
sensor2_isbotnet.head()

,Dur,Proto,SrcAddr,Sport,Dir,DstAddr,Dport,State,sTos,dTos,TotPkts,TotBytes,SrcBytes,StartTimeHour,StartTimeMinute,StartTimeSecond,isBotnet
0,20.00,3,14610,75,0,141,581761,82,0,0,7,424,242,11,43,1,0
1,0.00,4,462414,109,3,1621520,1645689,16,0,0,2,240,95,9,25,52,0
2,0.00,4,1,63,3,1212234,1166534,16,0,0,2,131,71,10,29,47,0
3,0.07,3,462414,83,0,100,581761,104,0,0,10,2401,1000,9,28,36,0
4,0.00,4,811174,68,3,1621520,1645689,16,0,0,2,214,81,9,42,20,0

In [22]:
sensor2_isbotnet.to_csv(dataset_dir + 'sensor2_isbotnet.csv', index=False)

## isSpam

In [23]:
sensor2_isspam = sensor2_train.copy()
sensor2_isspam = sensor2_isspam[sensor2_isspam['isBotnet'] == 1]
sensor2_isspam.head()

,Dur,Proto,SrcAddr,Sport,Dir,DstAddr,Dport,State,sTos,dTos,TotPkts,TotBytes,SrcBytes,Label,StartTimeHour,StartTimeMinute,StartTimeSecond,isBotnet,isSpam
6,0.03,3,20862,136,0,3720,581761,104,0,0,14,5335,647,1,12,37,24,1,0
18,62.33,3,77880,178,0,2897,581761,286,0,0,7,1112,733,1,15,59,4,1,0
29,0.00,0,20984,3704,0,1621520,370,316,0,0,1,102,102,1,10,28,20,1,0
36,1.09,3,20745,84,0,2216,148497,104,0,0,16,5622,1484,1,14,9,7,1,0
73,0.14,3,23960,147,0,4036,581761,104,0,0,10,1611,725,1,11,17,46,1,0

In [24]:
sensor2_isspam = sensor2_isspam.drop(columns=['Label', 'isBotnet'])

In [25]:
sensor2_isspam.head()

,Dur,Proto,SrcAddr,Sport,Dir,DstAddr,Dport,State,sTos,dTos,TotPkts,TotBytes,SrcBytes,StartTimeHour,StartTimeMinute,StartTimeSecond,isSpam
6,0.03,3,20862,136,0,3720,581761,104,0,0,14,5335,647,12,37,24,0
18,62.33,3,77880,178,0,2897,581761,286,0,0,7,1112,733,15,59,4,0
29,0.00,0,20984,3704,0,1621520,370,316,0,0,1,102,102,10,28,20,0
36,1.09,3,20745,84,0,2216,148497,104,0,0,16,5622,1484,14,9,7,0
73,0.14,3,23960,147,0,4036,581761,104,0,0,10,1611,725,11,17,46,0

In [26]:
sensor2_isspam.to_csv(dataset_dir + 'sensor2_isspam.csv', index=False)

# Sensor 3

In [27]:
sensor3_train = pd.read_csv(dataset_dir + 'train3_encoded.csv')

In [28]:
sensor3_train.head()

,Dur,Proto,SrcAddr,Sport,Dir,DstAddr,Dport,State,sTos,dTos,TotPkts,TotBytes,SrcBytes,Label,StartTimeHour,StartTimeMinute,StartTimeSecond,isBotnet,isSpam
0,0.00,4,1,106,3,338987,318377,7,0,0,2,548,488,0,12,6,15,0,0
1,0.00,4,492764,50,3,1211113,1220778,7,0,0,2,214,81,0,12,27,40,0,0
2,1.24,3,6457,202,0,248,3257,76,0,0,53,17709,2206,0,11,22,43,0,0
3,"3,251.45",4,1,6,3,338987,318377,7,0,0,6,1270,232,0,9,20,12,0,0
4,0.00,4,440828,86,3,1211113,1220778,7,0,0,2,200,75,0,10,24,28,0,0

In [29]:
sensor3_train.shape

(2697486, 19)

## isBotnet

In [30]:
sensor3_isbotnet = sensor3_train.copy()
sensor3_isbotnet.head()

,Dur,Proto,SrcAddr,Sport,Dir,DstAddr,Dport,State,sTos,dTos,TotPkts,TotBytes,SrcBytes,Label,StartTimeHour,StartTimeMinute,StartTimeSecond,isBotnet,isSpam
0,0.00,4,1,106,3,338987,318377,7,0,0,2,548,488,0,12,6,15,0,0
1,0.00,4,492764,50,3,1211113,1220778,7,0,0,2,214,81,0,12,27,40,0,0
2,1.24,3,6457,202,0,248,3257,76,0,0,53,17709,2206,0,11,22,43,0,0
3,"3,251.45",4,1,6,3,338987,318377,7,0,0,6,1270,232,0,9,20,12,0,0
4,0.00,4,440828,86,3,1211113,1220778,7,0,0,2,200,75,0,10,24,28,0,0

In [31]:
sensor3_isbotnet = sensor3_isbotnet.drop(columns=['Label', 'isSpam'])

In [32]:
sensor3_isbotnet.head()

,Dur,Proto,SrcAddr,Sport,Dir,DstAddr,Dport,State,sTos,dTos,TotPkts,TotBytes,SrcBytes,StartTimeHour,StartTimeMinute,StartTimeSecond,isBotnet
0,0.00,4,1,106,3,338987,318377,7,0,0,2,548,488,12,6,15,0
1,0.00,4,492764,50,3,1211113,1220778,7,0,0,2,214,81,12,27,40,0
2,1.24,3,6457,202,0,248,3257,76,0,0,53,17709,2206,11,22,43,0
3,"3,251.45",4,1,6,3,338987,318377,7,0,0,6,1270,232,9,20,12,0
4,0.00,4,440828,86,3,1211113,1220778,7,0,0,2,200,75,10,24,28,0

In [33]:
sensor3_isbotnet.to_csv(dataset_dir + 'sensor3_isbotnet.csv', index=False)

## isSpam

In [34]:
sensor3_isspam = sensor3_train.copy()
sensor3_isspam = sensor3_isspam[sensor3_isspam['isBotnet'] == 1]
sensor3_isspam.head()

,Dur,Proto,SrcAddr,Sport,Dir,DstAddr,Dport,State,sTos,dTos,TotPkts,TotBytes,SrcBytes,Label,StartTimeHour,StartTimeMinute,StartTimeSecond,isBotnet,isSpam
21,4.69,3,65253,102,0,751,4724,73,0,0,10,1011,568,1,14,25,35,1,0
23,93.50,3,16364,833,0,1946,16744,78,0,0,10,2248,2186,1,10,9,32,1,0
27,"3,566.99",3,65253,239,0,1375,117676,184,0,0,220,14760,8092,1,15,24,55,1,0
41,16.12,3,17236,71,0,60,469208,207,0,0,17,7634,863,1,15,16,53,1,0
49,12.69,3,65253,49,0,2273,9064,73,0,0,28,6190,4506,1,11,18,33,1,0

In [35]:
sensor3_isspam = sensor3_isspam.drop(columns=['Label', 'isBotnet'])

In [36]:
sensor3_isspam.head()

,Dur,Proto,SrcAddr,Sport,Dir,DstAddr,Dport,State,sTos,dTos,TotPkts,TotBytes,SrcBytes,StartTimeHour,StartTimeMinute,StartTimeSecond,isSpam
21,4.69,3,65253,102,0,751,4724,73,0,0,10,1011,568,14,25,35,0
23,93.50,3,16364,833,0,1946,16744,78,0,0,10,2248,2186,10,9,32,0
27,"3,566.99",3,65253,239,0,1375,117676,184,0,0,220,14760,8092,15,24,55,0
41,16.12,3,17236,71,0,60,469208,207,0,0,17,7634,863,15,16,53,0
49,12.69,3,65253,49,0,2273,9064,73,0,0,28,6190,4506,11,18,33,0

In [37]:
sensor3_isspam.to_csv(dataset_dir + 'sensor3_isspam.csv', index=False)